server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://sunat.postgres.database.azure.com:5432/sunat_db
    username: admin_azure
    password: Clasificador1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Configuración de logging (NUEVO)
logging:
  level:
    org.springframework: INFO  # Logs de Spring Framework
  file:
    name: D:/app/logs/application.log  # Archivo donde se guardarán los logs
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

sunat:
  api:
    url: https://ww1.sunat.gob.pe/ol-ti-itvisornoti/visor
    cookies: f5avraaaaaaaaaaaaaaaa_session_=MLAOCMGEAKOILNAIDGPCMODNGBE