
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sunat_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

sunat:
  api:
    url: https://ww1.sunat.gob.pe/ol-ti-itvisornoti/visor/listNotiMenPag
    cookies: f5_cspm=1234; f5avraaaaaaaaaaaaaaaa_session_=FPMLFMJ